import { environment } from 'src/environments/environment';

export const API = {

  seguridad: {
    oauth: environment.apiSeguridad + '/v1/auth/signin',
    eventoBitacora: environment.apiSeguridad + '/v1/auth/bitacora',
  },
  home:  '/home',
  login:  '/login',
  catalogos:{
    getUMF: environment.apiAdminMezclas + '/v1/unidadMedica/unidadMedicaList',
    getUnidadesMedicas: environment.apiCatalogos + '/v1/unidadMedica/searchFilters',
    getServiciosEspecialidadByCategoria: environment.apiCatalogos + '/v1/servicioEspecialidad/searchFilters',
    getCentralMezcla: environment.apiCatalogos + '/v1/centralMezcla',
    getPerfiles: environment.apiCatalogos + '/v1/perfil',
    getEstatusSolicitud: environment.apiCatalogos + '/v1/estatusSolicitud',
    getTipoMezcla: environment.apiCatalogos + '/v1/tipoMezcla',
    getServiciosEspecialidades: environment.apiCatalogos + '/v1/servicioEspecialidad',
    getMedicamentos: environment.apiCatalogos + '/v1/medicamento/searchFilters',
    getMedicamentosFiltro: environment.apiCatalogos + '/v1/medicamento/searchFilters',
    getDiluyentes: environment.apiCatalogos + '/v1/diluyente',
    getIntervaloAdmon: environment.apiCatalogos + '/v1/intervaloAdministracion',
    getDiagnosticos: environment.apiCatalogos + '/v1/diagnosticoCie',
    getViaAdmon: environment.apiCatalogos + '/v1/viaAdministracion',
    getMotivoRechazo: environment.apiCatalogos + '/v1/motivoRechazo',
    getfabricante: environment.apiCatalogos + '/v1/fabricante',
    getByRemision: environment.apiCatalogos + '/v1/farmacia/getByRemision',
    getConservacionMedica: environment.apiCatalogos + '/v1/conservacionMedica',
    getDiluyente: environment.apiCatalogos + '/v1/diluyente',
    getTurnoCampanas: environment.apiCatalogos + '/v1/turno/searchFilters',
    getAplicacionCada: environment.apiCatalogos + '/v1/aplicacionCada',
    getTiempoInfusion: environment.apiCatalogos + "/v1/tiempoInfusion",
    getTipoComponente: environment.apiCatalogos + "/v1/tipoComponente",
    getComponente: environment.apiCatalogos + '/v1/medicamento/searchFilters',
    getEstatusMezcla: environment.apiCatalogos + '/v1/estatusMezcla',
    getMotivoCancelacion: environment.apiCatalogos + '/v1/motivoCancelacion', 
    getMarcaByFabricante: environment.apiCatalogos + '/v1/marca', 
    getMarcaByFabricanteFT: environment.apiConsultas + '/v1/fichaTecnica?filter=catMarca/true', 
    getConservacionMedic: environment.apiCatalogos + '/v1/conservacionMedic',
    getCausaAtribuible: environment.apiCatalogos + '/v1/causaAtribuible',
    getMedidaCorrectiva: environment.apiCatalogos + '/v1/medidaCorrectiva',
    getTurno: environment.apiCatalogos + '/v1/turno',
    getTurnoCampana: environment.apiCatalogos + '/v1/turnoCampana',
    getLotes: environment.apiConsultas + '/v1/regMedic?filter=consLotes/true',
    getProveedorDistribucion: environment.apiCatalogos + '/v1/proveedorDistribucion',
    getMotivoReimpresion: environment.apiCatalogos + '/v1/motivoReimpresion',
    getReaccionesAdversas: environment.apiCatalogos + '/v1/reaccionesAdversas',
    getMotivoNoAdminMezcla: environment.apiCatalogos + '/v1/motivoNoadminMezcla',
    getFabricanteByMed: environment.apiCatalogos + '/v1/catFicha?filter=fabXFicha/true=idMedicamento',
    getFichaTecnicaTipoPeriodoValidez: environment.apiCatalogos + '/v1/tipoPeriodoValidez',
    getRecomendacionEtiqueta: environment.apiCatalogos + '/v1/recomendacionEtiqueta',
  },
  consultas:{
    saveSolicitud:environment.apiConsultas + '/v1/solicitud',
    getSolicitudesPre:environment.apiConsultas + '/v1/prescripcion/buscarSolicitudesPrescripcion',
    getDetalleMezclaPre:environment.apiConsultas+ '/v1/prescripcion/detalleMezcla',
    aprobarMezclaPre:environment.apiConsultas+ '/v1/prescripcion/aprobarMezcla',
    rechazarMezclaPre:environment.apiConsultas+ '/v1/prescripcion/rechazarMezcla', 
    getDetalleMezclaPreNtp:environment.apiConsultas+'/v1/prescripcion/detalleNPT',
    getSolicitudesResolucion:environment.apiConsultas + '/v1/resolucionInvestigacion/buscarSolicitudesResolucion',
    getReporteAprobadasPre:environment.apiConsultas + '/v1/prescripcion/generarReporteAprobadas',
    getDetalleMezclaPreCitotoxico:environment.apiConsultas + '/v1/prescripcion/detalleCitotoxico',
    getValidaTipoMezclaFlag: environment.apiConsultas + '/v1/notaMedica/validaTipoMezclaFlag',
    getDetalleCitotoxico:environment.apiConsultas + '/v1/prescripcion/detalleCitotoxico',
    getDetalleNpt:environment.apiConsultas + '/v1/prescripcion/detalleNPT',
    getTurnoCampana: environment.apiConsultas + '/v1/turnoCampana/buscarSolicitudes',
    getRecetaColectivaMedicamentos: environment.apiConsultas + '/v1/regMedic',
    validaRecetaColectiva: environment.apiConsultas + '/v1/fichaTecnica',
    validaFichaTecnica: environment.apiConsultas + '/v1/fichaTecnica',
    actualizarMedicamentoRecetaColectiva: environment.apiConsultas + '/v1/regMedic',
    registrarRecetaCollectiva:environment.apiConsultas+'/v1/regMedic/registrarReceta',
    guardarResolucion:environment.apiConsultas+'/v1/resolucionInvestigacion/guardarResolucion',
  
    getOrdenRecepcionUM:environment.apiConsultas+'/v1/preparadorMezcla/coordinador',
    getOrdenStatusRecepcionUM:environment.apiConsultas+'/v1/preparadorMezcla/coordinadorAfterUpdate',
    getlstMedicamentosTotal:environment.apiConsultas + '/v1/regMedic',
    getSolicitudesAcond:environment.apiConsultas + '/v1/acondicionamientoDistribucion/buscarSolicitudesAcondicionamiento',
    getSolicitudesDistribucion:environment.apiConsultas + '/v1/acondicionamientoDistribucion/buscarSolicitudesDistribucion',
    getAsignarProveedor:environment.apiConsultas + '/v1/acondicionamientoDistribucion/asociarProveedor',
    imprimeEtiqueta:environment.apiConsultas + '/v1/acondicionamientoDistribucion/imprimirEtiqueta',
    imprimeOrden:environment.apiConsultas + '/v1/acondicionamientoDistribucion/imprimirOrdenEntrega',
    noAprobarMezcla:environment.apiConsultas + '/v1/acondicionamientoDistribucion/noAprobar',
    validaCerrarMezcla:environment.apiConsultas + '/v1/acondicionamientoDistribucion/cerrar',
    validaReimpresion:environment.apiConsultas + '/v1/acondicionamientoDistribucion/solicitarReimpresion',
    getevalReimEtiqueta:environment.apiConsultas + '/v1/evalReimEtiqueta',
    getFechasCad: environment.apiConsultas + '/v1/regMedic',
    confirmarOrdenUM: environment.apiConsultas + '/v1/preparadorMezcla/confirmarOrden',
    getValidaNumReimpresion:environment.apiConsultas + '/v1/acondicionamientoDistribucion/validarNumeroImpresiones',
    preAprobarPreparada:environment.apiConsultas + '/v1/acondicionamientoDistribucion/aprobarPreparada',
    evalReimEtiqueta:environment.apiConsultas+'/v1/evalReimEtiqueta',
    saveLotes: environment.apiConsultas + '/v1/regMedic/asignacionMed',
    asignacionMezcla: environment.apiConsultas + '/v1/turnoCampana',
    consultaLotesMed: environment.apiConsultas + '/v1/regMedic?filter=medLotTur/true=',
    updateFT: environment.apiConsultas + '/v1/fichaTecnica',
    usuarioPheds:environment.apiConsultas + '/v1/usuarioPheds',
    consultaMedicamentoSAI:environment.apiConsultas + '/v1/regMedic/consultaMed',
    consultaDelegacion:environment.apiConsultas + '/v1/usuarioPheds/delegacion',
  },
  seguimiento:{
    datosPaciente: environment.apiConsultas + '/v1/seguimientoMezcla/paciente',
    historialMezclas: environment.apiConsultas + '/v1/seguimientoMezcla/historial',
    cancelar: environment.apiConsultas + '/v1/seguimientoMezcla/cancelar',
    ratificar: environment.apiConsultas + '/v1/seguimientoMezcla/ratificar',
    detalleDias: environment.apiConsultas + '/v1/prescripcion/detalleDias',
  },
  seguimientoGeneral:{
    
    historialMezclas: environment.apiConsultas + '/v1/seguimientoMezcla/historial',
    
   
  },
  aplicacionMezcla:{
    
    historialMezclas: environment.apiConsultas + '/v1/aplicacionMezcla/esteriles',
    signosVitales: environment.apiConsultas + '/v1/aplicacionMezcla/signosVitales',
    turno: environment.apiConsultas + '/v1/aplicacionMezcla/turno',
    iniciarAplicacion: environment.apiConsultas + '/v1/aplicacionMezcla/iniciarAplicacion',
    finalizarAplicacion: environment.apiConsultas + '/v1/aplicacionMezcla/finalizarAplicacion',
    noAplicar: environment.apiConsultas + '/v1/aplicacionMezcla/noAplicar',
    
   
  },
  preparacionMezcla:{
    busqueda: environment.apiConsultas + '/v1/preparadorMezcla/busquedaPreparacionMezcla',
    detalle: environment.apiConsultas + '/v1/preparadorMezcla',
    finaliza: environment.apiConsultas + '/v1/preparadorMezcla/finalizarPreparacion',
    loteMed: environment.apiConsultas + '/v1/preparadorMezcla/lotes',
    guardaCaducidad : environment.apiConsultas + '/v1/preparadorMezcla/imprimir',
    fichaTecnica: environment.apiConsultas + '/v1/preparadorMezcla/fichaTecMed',
    codigoBarras: environment.apiConsultas + '/v1/preparadorMezcla/codigoBarras'
  },
  reportes:{
     getDataReporteRecepcionUM: environment.apiReportes + '/v1/rechazoDistribuidor/datosReporte',
     getDataReporteOrdenEntrega: environment.apiReportes + '/v1/rechazoDistribuidor/datosReporteMezclas',
   
  }
}

